### PR TITLE
Bug: Patch Failing Dockerfile

### LINKED ISSUE #106: Bug: Patch Failing Docker Image
The Dockerfile needs to be updated to include this patch:
https://github.com/xmidt-org/tr1d1um/commit/df49bb536fa91ca46fec6384534ddc674406a2b9

Steps:
- [x] fix breaking JWK changes
- [x] fix unit tests
- [x] fix linter errors
- [x] replace deprecated library usage of Maintainer

### PR DESCRIPTION
**Pull request by denopink**
## What's included:
- Patch failing build layers
- Remove deprecated `MAINTAINER`

Fixes #106 

https://github.com/comcast-cl/xmidt/issues/446
https://github.com/comcast-cl/xmidt/issues/435

### CODE REVIEW

**Review by johnabass — APPROVED** [review]

File: key/endpoint_test.go [hunk 1]
```diff
@@ -49,9 +50,9 @@ func TestNewEndpoint(t *testing.T) {
 		require.Error(err)
 		require.Nil(result)
 
-		knfe, ok := err.(KeyNotFoundError)
+		var keyNotFoundError KeyNotFoundError
```
Comment (johnabass) [inline key/endpoint_test.go:53]: `github.com/stretchr/testify/assert` and `github.com/stretchr/testify/require` both have `ErrorIs` and `ErrorAs` assertions.  you can use those to do these kinds of assertions in just 1-2 lines of code.

**Review by johnabass — CHANGES_REQUESTED** [review]

**Review by schmidtw — APPROVED** [review]

File: key/endpoint_test.go (hunk 1 above)
Comment (renaz6) [reply key/endpoint_test.go:51]: Thanks for the suggestion! I fixed it.
